import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';
import 'package:emoji_picker_flutter/locales/default_emoji_set_locale.dart';
import 'package:flutter/widgets.dart';

List<CategoryEmoji> emojiSetWithUnicode17(Locale locale) {
  final baseSet = getDefaultEmojiLocale(locale);
  final baseCategories = {
    for (final category in baseSet) category.category,
  };
  final emojiByCategory = <Category, List<Emoji>>{
    for (final category in baseSet)
      category.category: List<Emoji>.from(category.emoji),
  };
  final emojiValuesByCategory = <Category, Set<String>>{
    for (final category in baseSet)
      category.category: category.emoji.map((emoji) => emoji.emoji).toSet(),
  };

  for (final category in unicode17EmojiSet) {
    final list = emojiByCategory.putIfAbsent(category.category, () => []);
    final existing =
        emojiValuesByCategory.putIfAbsent(category.category, () => <String>{});
    for (final emoji in category.emoji) {
      if (existing.add(emoji.emoji)) {
        list.add(emoji);
      }
    }
  }

  final merged = <CategoryEmoji>[
    for (final category in baseSet)
      CategoryEmoji(category.category, emojiByCategory[category.category]!),
  ];

  for (final category in emojiByCategory.entries) {
    if (!baseCategories.contains(category.key)) {
      merged.add(CategoryEmoji(category.key, category.value));
    }
  }

  return merged;
}

// Unicode 17.0 additions (base emojis only; skin tone variants are generated by the picker).
const List<CategoryEmoji> unicode17EmojiSet = [
  CategoryEmoji(Category.SMILEYS, [
    Emoji('🫪', 'distorted face'),
    Emoji('🫯', 'fight cloud'),
    Emoji('🫈', 'hairy creature'),
  ]),
  CategoryEmoji(Category.ACTIVITIES, [
    Emoji('🧑‍🩰', 'ballet dancer', hasSkinTone: true),
  ]),
  CategoryEmoji(Category.ANIMALS, [
    Emoji('🫍', 'orca'),
  ]),
  CategoryEmoji(Category.TRAVEL, [
    Emoji('🛘', 'landslide'),
  ]),
  CategoryEmoji(Category.OBJECTS, [
    Emoji('🪊', 'trombone'),
    Emoji('🪎', 'treasure chest'),
  ]),
];
