import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

// Unicode 17.0 additions (base emojis only; skin tone variants are generated by the picker).
const List<CategoryEmoji> unicode17EmojiSet = [
  CategoryEmoji(Category.SMILEYS, [
    Emoji('🫪', 'distorted face'),
    Emoji('🫯', 'fight cloud'),
    Emoji('🫈', 'hairy creature'),
  ]),
  CategoryEmoji(Category.ACTIVITIES, [
    Emoji('🧑‍🩰', 'ballet dancer', hasSkinTone: true),
  ]),
  CategoryEmoji(Category.ANIMALS, [
    Emoji('🫍', 'orca'),
  ]),
  CategoryEmoji(Category.TRAVEL, [
    Emoji('🛘', 'landslide'),
  ]),
  CategoryEmoji(Category.OBJECTS, [
    Emoji('🪊', 'trombone'),
    Emoji('🪎', 'treasure chest'),
  ]),
];
